### ISSUE TITLE
Roadmap (long-term)

### ISSUE THREAD

**Issue by ethanwhite** [weecology/biodivcast#1]
## Data
Look into including new predictor variables:
- [ ] non-linear combinations of environmental factors
- [ ] land cover
- [ ] different spatial scales for environment
- [ ] species life history (bonus, non-trivial to obtain?)

## Modeling

- [ ] GJAM (see [R package](https://cran.r-project.org/web/packages/gjam/index.html))
- [ ] zoon (see [R package](https://github.com/zoonproject/zoon))
- [ ] establish baselines for prediction (cross-listed to `Automated Evaluation`)
- [ ] in house modeling
    * time-series methods being developed for Portal forecasting
    * abundance based forecasting methods

## Automated Evaluation

- [ ] develop proof of concept for Jenkins on Hipergator
- [ ] implement Jenkins/Hipergator for Continuous Analysis
- [ ] define evaluation metrics
- [ ] integration of multiple datasets
  plan for:
  * common inputs
    - environmental matrix
    - abundance matrix
  * common outputs
    - log likelihood
    - predictions + uncertainty
    - species specific metrics
- [ ] predictions under future scenarios
